
name: Jekyll site CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2



    - name: Custom site generation
      run: |

        # This could be outsourced to a separate bash script if it becomes
        # lengthy

        cp _layouts/default-template.html _layouts/default.html

        export TZ='US/Eastern'
        date=$(date)
        revi=$(git rev-parse --short HEAD)

        sed -i "s/\<BUILD\_DATE\>/$date/g" _layouts/default.html
        sed -i "s/\<BUILD\_REVI\>/$revi/g" _layouts/default.html



    - uses: actions/jekyll-build-pages@v1-beta

    - name: Deploy to github pages
      uses: JeffIrwin/github-pages-deploy-action@4.1.8
      with:
        branch: main
        folder: .

