
name: Github pages custom publish workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: JeffIrwin/gh-pages-deploy-action@v1.1
      - name: custom run
        run: |
          date > _includes/footer.md

